# Generated by Django 3.1.2 on 2020-11-13 17:55

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0023_auto_20201113_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='group',
            field=models.ManyToManyField(blank=True, default=[], to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, editable=False, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
